apiVersion: v1
kind: Service
metadata:
  name: my-defid-service
  namespace: defid
spec:
  selector:
    app.kubernetes.io/name: defid-docker
  ports:
    - protocol: TCP
      port: 8554
      targetPort: 8554
