apiVersion: v1
kind: PersistentVolume
metadata:
  name: defid-local-pv
spec:
  capacity:
    storage: 2048Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /defid-persistence
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - defilense.com
