apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: defid-pv-claim
  namespace: defid
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2048Gi
