apiVersion: v1
kind: Pod
metadata:
  name: defid-indexer-docker
  namespace: defid
  labels:
    app.kubernetes.io/name: defid-indexer-docker
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - defilense.com
  containers:
    - name: defid-indexer-docker
      image: muirglacier/defid-indexer:latest
      env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: indexer-secrets
              key: USER
              optional: false
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: indexer-secrets
              key: PASS
              optional: false
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: indexer-secrets
              key: HOST
              optional: false
        - name: MONGODB
          valueFrom:
            secretKeyRef:
              name: indexer-secrets
              key: MONGODB
              optional: false

